quarkus:
  http:
    port: 8080

ebean:
  dbSchema: my_app      # use this schema rather than public
  migration:
    run: true           # run database migrations on startup

datasource:
  db:
    username: portal
    password: portal
    url: jdbc:postgresql://localhost:30002/books